-- MySQL Script generated by MySQL Workbench
-- Mon Jul  1 10:04:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cobosHubBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cobosHubBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cobosHubBD` DEFAULT CHARACTER SET utf8 ;
USE `cobosHubBD` ;

-- -----------------------------------------------------
-- Table `cobosHubBD`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobosHubBD`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NULL,
  `apPaternoUsuario` VARCHAR(45) NULL,
  `apMaternoUsuario` VARCHAR(45) NULL,
  `emailUsuario` VARCHAR(45) NULL,
  `telUsuario` VARCHAR(45) NULL,
  `fotoUsuario` LONGBLOB NULL,
  `estatusUsuario` TINYINT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cobosHubBD`.`rolusuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobosHubBD`.`rolusuario` (
  `idrolusuario` INT NOT NULL AUTO_INCREMENT,
  `nombreRolUsuario` VARCHAR(45) NULL,
  `descripcionRolUsuario` VARCHAR(45) NULL,
  PRIMARY KEY (`idrolusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cobosHubBD`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobosHubBD`.`login` (
  `idlogin` INT NOT NULL AUTO_INCREMENT,
  `nombreLogin` VARCHAR(45) NULL,
  `claveLogin` VARCHAR(256) NULL,
  `fechaCreacionLogin` DATE NULL,
  `estatusLogin` VARCHAR(45) NULL,
  `idUsuaro` INT NULL,
  `idRolUsuario` INT NULL,
  PRIMARY KEY (`idlogin`),
  INDEX `fk_usuario_login_idx` (`idUsuaro` ASC) VISIBLE,
  INDEX `fk_rolusuario_login_idx` (`idRolUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_login`
    FOREIGN KEY (`idUsuaro`)
    REFERENCES `cobosHubBD`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rolusuario_login`
    FOREIGN KEY (`idRolUsuario`)
    REFERENCES `cobosHubBD`.`rolusuario` (`idrolusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `cobosHubBD`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `cobosHubBD`;
INSERT INTO `cobosHubBD`.`usuario` (`idusuario`, `nombreUsuario`, `apPaternoUsuario`, `apMaternoUsuario`, `emailUsuario`, `telUsuario`, `fotoUsuario`, `estatusUsuario`) VALUES (01, 'Jorge Alberto', 'Rodríguez ', 'Enríquez', '23301800@uttt.edu.mx', '7295174356', NULL, NULL);
INSERT INTO `cobosHubBD`.`usuario` (`idusuario`, `nombreUsuario`, `apPaternoUsuario`, `apMaternoUsuario`, `emailUsuario`, `telUsuario`, `fotoUsuario`, `estatusUsuario`) VALUES (DEFAULT, 'Alexander ', 'Dominguez', 'Zarate', '23301324@uttt.edu.mx', '5559879544', NULL, NULL);
INSERT INTO `cobosHubBD`.`usuario` (`idusuario`, `nombreUsuario`, `apPaternoUsuario`, `apMaternoUsuario`, `emailUsuario`, `telUsuario`, `fotoUsuario`, `estatusUsuario`) VALUES (DEFAULT, 'David', 'Ramirez', 'Aguilar', '23300082@uttt.edu.mx', '7731165643', NULL, NULL);
INSERT INTO `cobosHubBD`.`usuario` (`idusuario`, `nombreUsuario`, `apPaternoUsuario`, `apMaternoUsuario`, `emailUsuario`, `telUsuario`, `fotoUsuario`, `estatusUsuario`) VALUES (DEFAULT, 'Eliuht', 'Granados', 'Vargas', '23300043@uttt.edu.mx', '7731267863', NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `cobosHubBD`.`rolusuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `cobosHubBD`;
INSERT INTO `cobosHubBD`.`rolusuario` (`idrolusuario`, `nombreRolUsuario`, `descripcionRolUsuario`) VALUES (DEFAULT, 'administrador', 'tiene todos los permisos');
INSERT INTO `cobosHubBD`.`rolusuario` (`idrolusuario`, `nombreRolUsuario`, `descripcionRolUsuario`) VALUES (DEFAULT, 'cliente ', 'solo tiene permiso de consulta');
INSERT INTO `cobosHubBD`.`rolusuario` (`idrolusuario`, `nombreRolUsuario`, `descripcionRolUsuario`) VALUES (DEFAULT, 'invitado ', 'mirar no tocar');

COMMIT;

